#pragma config(Motor,  port2,           rightBmotor,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftBmotor,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           strafe,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rightArm,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           leftArm,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,            ,             tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
    //clear encoders
    SensorValue[wheelEncoder] = 0;
    SensorValue[armEncoder] = 0;
    SensorValue[clawEncoder] = 0;
    
    //drive forward to middle tape
    while(SensorValue[wheelEncoder] < 550){
        motor[rightBmotor] = 127;
        motor[rightFmotor] = 127;
        motor[leftBmotor] = 127;
        motor[leftFmotor] = 127;
    }
    //clear encoder, stop driving, and wait
    motor[rightBmotor] = 0;
    motor[rightFmotor] = 0;
    motor[leftBmotor] = 0;
    motor[leftFmotor] = 0;
    SensorValue[wheelEncoder] = 0;
    wait1Msec(400);
    
    //turn 90 degrees towards cube
    while(SensorValue[wheelEncoder] < 450){
        motor[rightBmotor] = 127;
        motor[rightFmotor] = 127;
        motor[leftBmotor] = -127;
        motor[leftFmotor] = -127;
    }
    //clear encoder and stop driving
    motor[rightBmotor] = 0;
    motor[rightFmotor] = 0;
    motor[leftBmotor] = 0;
    motor[leftFmotor] = 0;
    SensorValue[wheelEncoder] = 0;
    
    //open claw
    while(SensorValue[clawEncoder] < 67){
        motor[Claw] = 127;
    }
    //clear encoder, stop opening, and wait
    motor[Claw] = 0;
    SensorValue[clawEncoder] = 0;
    wait1Msec(100);
    
    //drive fowards towards cube
    while(SensorValue[wheelEncoder] < 600){
        motor[rightBmotor] = 127;
        motor[rightFmotor] = 127;
        motor[leftBmotor] = 127;
        motor[leftFmotor] = 127;
    }
    //clear encoder, stop driving, and wait
    motor[rightBmotor] = 0;
    motor[rightFmotor] = 0;
    motor[leftBmotor] = 0;
    motor[leftFmotor] = 0;
    SensorValue[wheelEncoder] = 0;
    wait1Msec(100);
    
    //close claw
    while(SensorValue[clawEncoder] < 100){
        motor[Claw] = 127;
    }
    //clear encoder, low power to grip cube, and wait
    motor[Claw] = 50;
    SensorValue[clawEncoder] = 0;
    wait1Msec(100);
    
    //lift arm a little
    while(SensorValue[armEncoder] > -100){
        motor[rightArm] = 50;
        motor[leftArm] = 50;
        motor[extraMotors] = 50;
    }
    //clear encoder, stop lift, and wait
    motor[rightArm] = 0;
    motor[leftArm] = 0;
    motor[extraMotors] = 0;
    SensorValue[armEncoder] = 0;
    wait1Msec(500);
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
    //forever loop
    while (true)
    {
        //drive with left joystick via addition of vectors
        motor[leftBmotor]  =  vexRT[Ch3] + vexRT[Ch4];
        motor[rightBmotor] =  vexRT[Ch3] - vexRT[Ch4];
        motor[leftFmotor]  =  vexRT[Ch3] + vexRT[Ch4];
        motor[rightFmotor] =  vexRT[Ch3] - vexRT[Ch4];
    
        /*
        strafe wheel using right joystick
        motor[strafe] = vexRT[Ch1];
        */

        //arm motors controlled by buttons 6U and 6D
        if(vexRT[Btn6U] == 1)
        {
            //arm up
            motor[rightArm]= 127;
            motor[leftArm]= 127;
            motor[extraMotors]= 127;
        }
        else
        {
            //arm down
            if(vexRT[Btn6D] == 1)
            {
                motor[rightArm]= -127;
                motor[leftArm]= -127;
                motor[extraMotors]= -127;
            }
            else
            {
                //stay still
                motor[rightArm]= 0;
                motor[leftArm]= 0;
                motor[extraMotors]= 0;
            }
        }

        //claw motors controlled by buttons 8R and 8L
        if(vexRT[Btn8R] == 1)
        {
            //close claw
            motor[claw]= 50;
        }
        else
        {
            if(vexRT[Btn8L] == 1)
            {
                //open claw
                motor[claw]= -50;
            }
            else
            {
                //stay still
                motor[claw]= 0;
            }
        }
    }
}
